'use client';
import {useState} from 'react';
import {Bell,ChevronRight,Gamepad2,Menu,Shield,Target,Trophy,Users} from 'lucide-react';
import {BottomNav} from './nav';
const ranking=[['Emanuel','7','+17','21'],['Pedro','8','+12','18'],['Carlos','7','+8','16'],['João','8','+2','13'],['Rafael','7','-1','10']];
const results=[['Carlos','1','3','Pedro'],['Rafael','5','4','Bruno'],['Lucas','2','2','André']];
const stats=[{Icon:Users,value:'8',label:'jogadores'},{Icon:Gamepad2,value:'15/56',label:'jogos'},{Icon:Target,value:'4ª',label:'rodada'}];
export function Dashboard(){const [tab,setTab]=useState<'geral'|'meu'>('geral');return <main className="safe-bottom mx-auto min-h-screen max-w-xl px-4 pt-5">
  <header className="mb-7 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-pitch text-ink shadow-glow"><Trophy size={25} strokeWidth={2.7}/></div><div><div className="text-lg font-black tracking-tight">COPA <span className="text-pitch">RESENHA</span></div><p className="text-[10px] font-semibold uppercase tracking-[.19em] text-muted">Futebol virtual. Resenha real.</p></div></div><button className="relative rounded-full border border-white/10 p-2.5"><Bell size={19}/><i className="absolute right-1 top-1 h-2 w-2 rounded-full bg-pitch"/></button></header>
  <section className="card relative mb-4 overflow-hidden p-5 shadow-glow"><div className="absolute -right-8 -top-10 h-32 w-32 rounded-full border-[22px] border-pitch/5"/><div className="relative"><div className="mb-3 flex items-center justify-between"><span className="tag text-pitch">Em andamento</span><span className="text-xs text-muted">Temporada 2026</span></div><h1 className="text-2xl font-black">Copa Resenha 2026</h1><p className="mt-1 text-sm text-muted">Pontos corridos · Ida e volta</p><div className="mt-6 grid grid-cols-3 gap-2 border-t border-white/10 pt-4">{stats.map(({Icon,value,label})=><div key={label} className="flex gap-2"><Icon className="mt-1 text-pitch" size={16}/><div><strong className="block text-sm">{value}</strong><span className="text-[10px] text-muted">{label}</span></div></div>)}</div></div></section>
  <div className="mb-4 grid grid-cols-2 rounded-xl bg-white/[.04] p-1 text-xs font-bold"><button onClick={()=>setTab('geral')} className={`rounded-lg py-2.5 ${tab==='geral'?'bg-white/10 text-white':'text-muted'}`}>Visão geral</button><button onClick={()=>setTab('meu')} className={`rounded-lg py-2.5 ${tab==='meu'?'bg-white/10 text-white':'text-muted'}`}>Meu desempenho</button></div>
  <div className="mb-3 flex items-center justify-between"><h2 className="tag text-muted">⚔ Próximo desafio</h2><span className="tag text-amber-400">Rodada 5</span></div>
  <section className="card mb-7 overflow-hidden"><div className="grid grid-cols-[1fr_auto_1fr] items-center p-5 text-center"><Player initials="EM" name="Emanuel" active/><div><span className="block text-[10px] font-bold text-muted">AGUARDANDO</span><strong className="my-1 block text-xl italic text-pitch">VS</strong><span className="text-[10px] text-muted">Resultado</span></div><Player initials="JO" name="João"/></div><button className="flex w-full items-center justify-center gap-2 border-t border-white/10 bg-pitch/10 py-3 text-xs font-black text-pitch">VER PARTIDA <ChevronRight size={15}/></button></section>
  <div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black">Classificação</h2><button className="text-xs font-bold text-pitch">Ver tabela</button></div>
  <section className="card mb-7 overflow-hidden"><div className="grid grid-cols-[30px_1fr_30px_40px_40px] border-b border-white/10 px-4 py-3 text-[9px] font-bold text-muted"><span>POS</span><span>JOGADOR</span><span>J</span><span>SG</span><span>PTS</span></div>{ranking.map((r,i)=><div key={r[0]} className={`grid grid-cols-[30px_1fr_30px_40px_40px] items-center px-4 py-3 text-xs ${i<ranking.length-1?'border-b border-white/[.06]':''}`}><b className={i===0?'text-pitch':''}>{i===0?'🥇':i+1}</b><span className="font-bold">{r[0]}</span><span className="text-muted">{r[1]}</span><span className={r[2][0]==='-'?'text-rose-400':'text-muted'}>{r[2]}</span><strong>{r[3]}</strong></div>)}</section>
  <div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black">Últimos resultados</h2><button className="text-xs font-bold text-pitch">Ver todos</button></div>
  <section className="card mb-5 divide-y divide-white/[.06]">{results.map(r=><div className="grid grid-cols-[1fr_auto_1fr] items-center px-4 py-3 text-xs" key={r.join('')}><span className="font-semibold">{r[0]}</span><strong className="rounded-lg bg-white/[.06] px-3 py-1.5 text-base">{r[1]} <i className="px-1 text-muted">×</i> {r[2]}</strong><span className="text-right font-semibold">{r[3]}</span></div>)}</section>
  <BottomNav/></main>}
function Player({initials,name,active=false}:{initials:string,name:string,active?:boolean}){return <div><div className={`mx-auto mb-2 grid h-16 w-16 place-items-center rounded-full border-2 text-lg font-black ${active?'border-pitch bg-pitch/10 text-pitch':'border-white/10 bg-white/5'}`}>{initials}</div><strong className="text-sm">{name}</strong></div>}
